language: ruby
sudo: required
dist: xenial
rvm:
  - 2.3.3
  - 2.4.0
  - jruby-9.1.5.0
  - rbx-2
  - jruby-head
before_install:
  - gem update bundler
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
